hits <- readr::read_tsv(file = "data-raw/from_website/hits.txt",
                        skip = 4)
sites <- readr::read_tsv(file = "data-raw/from_website/sites.txt",
                        skip = 4)
experiments <- readr::read_tsv(file = "data-raw/from_website/studies.txt",
                               skip = 4)
dhhcs <- readr::read_tsv(file = "data-raw/from_website/pats_and_apts.txt",
                         skip = 4)
proteins <- readr::read_tsv(file = "data-raw/from_website/proteins.txt",
                               skip = 4)